version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=assignment
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./
    restart: unless-stopped
    ports:
      - 3050:3050
    environment:
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=assignment
      - DB_PORT=3306
      - PORT=3050
    links:
      - mysqldb:mysqldb
    stdin_open: true
    tty: true

volumes:
  db:
